CREATE DATABASE SISTEMACITASMEDICAS
CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;
USE SISTEMACITASMEDICAS;

SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS CITA;
DROP TABLE IF EXISTS DOCTOR;
DROP TABLE IF EXISTS HISTORIA_CLINICA;
DROP TABLE IF EXISTS MEDICAMENTO;
DROP TABLE IF EXISTS PACIENTE;
DROP TABLE IF EXISTS TRATAMIENTO;
DROP TABLE IF EXISTS TRATAMIENTO_MEDICAMENTO;
DROP TABLE IF EXISTS USUARIO;

SET FOREIGN_KEY_CHECKS = 1;

CREATE TABLE USUARIO
(
    ID_USUARIO INT NOT NULL AUTO_INCREMENT,
    CEDULA VARCHAR(10) UNIQUE,
    NOMBRE VARCHAR(50),
    APELLIDO VARCHAR(50),
    EMAIL VARCHAR(100) UNIQUE,
    CONTRASENA VARCHAR(100),
    TELEFONO VARCHAR(10),
    ROL VARCHAR(1),
    ESTADO_USUARIO BOOLEAN,
    CHECK (CEDULA REGEXP '^[0-9]{10}$'),
    CHECK (ROL IN ('P','D','O')),
    CHECK (ESTADO_USUARIO IN (0,1)),
    CHECK (TELEFONO REGEXP '^[0-9]{7,10}$'),
    PRIMARY KEY (ID_USUARIO)
);

CREATE TABLE DOCTOR
(
    ID_DOCTOR INT NOT NULL AUTO_INCREMENT,
    ID_USUARIO INT UNIQUE,
    ESPECIALIDAD VARCHAR(100),
    FECHA_CONTRATO DATE,
    PRIMARY KEY (ID_DOCTOR)
);

CREATE TABLE HISTORIA_CLINICA
(
    ID_HISTORIA INT NOT NULL AUTO_INCREMENT,
    ID_PACIENTE INT UNIQUE,
    FECHA_INICIO_HISTORIA DATE,
    PRIMARY KEY (ID_HISTORIA)
);

CREATE TABLE PACIENTE
(
    ID_PACIENTE INT NOT NULL AUTO_INCREMENT,
    ID_USUARIO INT UNIQUE,
    SEXO VARCHAR(1),
    DIRECCION VARCHAR(200),
    FECHA_NACIMIENTO DATE,
    GRUPO_SANGUINEO VARCHAR(3),
    PESO DECIMAL(5,2),
    ALTURA DECIMAL(5,2),
    CHECK (SEXO IN ('M','F','O')),
    CHECK (GRUPO_SANGUINEO IN ('A+','A-','B+','B-','AB+','AB-','O+','O-')),
    CHECK (PESO > 0),
    CHECK (ALTURA > 0),
    PRIMARY KEY (ID_PACIENTE)
);
CREATE TABLE CITA
(
    ID_CITA INT NOT NULL AUTO_INCREMENT,
    ID_PACIENTE INT,
    ID_DOCTOR INT,
    FECHA_CITA DATE,
    HORA_INICIO TIME,
    MOTIVO_CONSULTA VARCHAR(200),
    OBSERVACIONES TEXT,
    ESTADO_CITA VARCHAR(1),
    CHECK (ESTADO_CITA IN ('P','C','A')),
    PRIMARY KEY (ID_CITA)
);

CREATE TABLE TRATAMIENTO
(
    ID_TRATAMIENTO INT NOT NULL AUTO_INCREMENT,
    ID_CITA INT UNIQUE,
    DESCRIPCION TEXT,
    FECHA_INICIO_TRATAMIENTO DATE,
    DURACION_DIAS INT,
    CHECK (DURACION_DIAS >= 0),
    PRIMARY KEY (ID_TRATAMIENTO)
);

CREATE TABLE MEDICAMENTO
(
    ID_MEDICAMENTO INT NOT NULL AUTO_INCREMENT,
    NOMBRE_MEDICAMENTO VARCHAR(100),
    EMPRESA VARCHAR(100),
    PRESENTACION VARCHAR(100),
    PRIMARY KEY (ID_MEDICAMENTO)
);

CREATE TABLE TRATAMIENTO_MEDICAMENTO
(
    ID_TRATAMIENTO INT NOT NULL,
    ID_MEDICAMENTO INT NOT NULL,
    DOSIS VARCHAR(50),
    FRECUENCIA VARCHAR(50),
    DURACION INT,
    CHECK (DURACION >= 0),
    PRIMARY KEY (ID_TRATAMIENTO, ID_MEDICAMENTO)
);

ALTER TABLE CITA
ADD CONSTRAINT FK_CITA_ACUDE_PACIENTE
FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTE(ID_PACIENTE);

ALTER TABLE CITA
ADD CONSTRAINT FK_CITA_ATIENDE_DOCTOR
FOREIGN KEY (ID_DOCTOR) REFERENCES DOCTOR(ID_DOCTOR);

ALTER TABLE DOCTOR
ADD CONSTRAINT FK_DOCTOR_ES_TAMBIE_USUARIO
FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO);

ALTER TABLE HISTORIA_CLINICA
ADD CONSTRAINT FK_HISTORIA_TIENE2_PACIENTE
FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTE(ID_PACIENTE);

ALTER TABLE PACIENTE
ADD CONSTRAINT FK_PACIENTE_ES_USUARIO
FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO);

ALTER TABLE TRATAMIENTO
ADD CONSTRAINT FK_TRATAMIE_DISPONE2_CITA
FOREIGN KEY (ID_CITA) REFERENCES CITA(ID_CITA);

ALTER TABLE TRATAMIENTO_MEDICAMENTO
ADD CONSTRAINT FK_TRATAMIE_TRATAMIEN_MEDICAME
FOREIGN KEY (ID_MEDICAMENTO) REFERENCES MEDICAMENTO(ID_MEDICAMENTO);

ALTER TABLE TRATAMIENTO_MEDICAMENTO
ADD CONSTRAINT FK_TRATAMIE_TRATAMIEN_TRATAMIE
FOREIGN KEY (ID_TRATAMIENTO) REFERENCES TRATAMIENTO(ID_TRATAMIENTO);
